In [1]:
import pandas as pd

In [2]:
# Estrutura de receitas
receitas = {
    "Brisket com Batata Frita": [
        {"produto": "Brisket Prime", "quantidade": 200, "unidade": "g"},
        {"produto": "Batata frita corte fino", "quantidade": 150, "unidade": "g"},
        {"produto": "Filtro p/ Café", "quantidade": 1, "unidade": "Un"}
    ],
    "Café com Copinho": [
        {"produto": "Filtro p/ Café", "quantidade": 1, "unidade": "Un"},
        {"produto": "Copinhos descartavel 80 ml - 100 unid", "quantidade": 1, "unidade": "Un"},
        {"produto": "Açúcar refinado", "quantidade": 10, "unidade": "g"}
    ],
    "Porção de Batata com Brisket Desfiado": [
        {"produto": "Batata frita corte fino", "quantidade": 200, "unidade": "g"},
        {"produto": "Brisket Prime", "quantidade": 100, "unidade": "g"},
        {"produto": "Colherinha de plástico pequena - c/500", "quantidade": 1, "unidade": "Un"}
    ]
}

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('data/receitas_brutas.xlsx')

df.head()

,Funghi,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,VALORES IMPORTANTES,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,"PARA EDITAR SEU ARQUIVO, FAÇA O SEGUINTE:",Unnamed: 11
0,INGREDIENTE,PREÇO,QUANTIDADE EMBALAGEM,UN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,IMPOSTOS,COMISSÕES,CUSTOS FIXOS,CUSTOS VARIÁVEIS,NaN,NaN,NaN
2,1. Bol para Creme 500ml,24,20,um,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1. Bolo G35M (Galvonotek),1.25,1,um,NaN,0,NaN,5000,NaN,NaN,NaN,NaN
4,1. Cartão Agradecimento,190,500,um,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import pandas as pd

arquivo = "data/receitas_brutas.xlsx"

xls = pd.ExcelFile(arquivo)

print(xls.sheet_names)

['CADASTRO DE INGREDIENTES', 'Arroz Integral', 'Pão Glúten', 'Creme Aipim', 'Base Bolo', 'Rosca Milho', 'Guisado Base', 'Mousse', 'Molho Branco', 'Canelone', ' Arroz Cozido', 'Frango Primavra', 'Risoto Base', 'Gororoba', 'Canja', 'Risoto de Funghi', 'Risoto Tomate Seco', 'Espaguete + Guisado', 'Porções', 'Mix Farinha', 'Guiado Base', 'Legumes + Guisado', 'Moranga + Guisadinho', 'Batata Doce + Guisadinho', 'Risoto Aspargos', 'Pao de Carne', 'Molho Vermelho', 'Vitamina', 'Pizza', 'Frango Grelhado', 'Molho Guisado', 'Almondegas C Molho', 'Arroz + Feijão', 'Massa Espaguete', 'Fricasse', 'Sanduiche', 'Bolo Assado', 'Guisado', 'Mix', 'Molho Frango', 'Sequilhos', 'Lasanha Abobrinha', 'Pudim', 'Risoto Frango', 'Frango Xadre', 'Salada Mix', 'Bolo Milho', 'Panquecas', 'Espinafre Panquca', 'Teste', 'Picadinho', 'Creme', 'Plan1']

In [9]:
lista_sheets = xls.sheet_names

lista_sheets = lista_sheets[1:]

lista_sheets

['Arroz Integral',
 'Pão Glúten',
 'Creme Aipim',
 'Base Bolo',
 'Rosca Milho',
 'Guisado Base',
 'Mousse',
 'Molho Branco',
 'Canelone',
 ' Arroz Cozido',
 'Frango Primavra',
 'Risoto Base',
 'Gororoba',
 'Canja',
 'Risoto de Funghi',
 'Risoto Tomate Seco',
 'Espaguete + Guisado',
 'Porções',
 'Mix Farinha',
 'Guiado Base',
 'Legumes + Guisado',
 'Moranga + Guisadinho',
 'Batata Doce + Guisadinho',
 'Risoto Aspargos',
 'Pao de Carne',
 'Molho Vermelho',
 'Vitamina',
 'Pizza',
 'Frango Grelhado',
 'Molho Guisado',
 'Almondegas C Molho',
 'Arroz + Feijão',
 'Massa Espaguete',
 'Fricasse',
 'Sanduiche',
 'Bolo Assado',
 'Guisado',
 'Mix',
 'Molho Frango',
 'Sequilhos',
 'Lasanha Abobrinha',
 'Pudim',
 'Risoto Frango',
 'Frango Xadre',
 'Salada Mix',
 'Bolo Milho',
 'Panquecas',
 'Espinafre Panquca',
 'Teste',
 'Picadinho',
 'Creme',
 'Plan1']

In [12]:
df_sheet = pd.read_excel(arquivo, sheet_name=lista_sheets[0])

df_sheet.head(50)

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,"PARA EDITAR SEU ARQUIVO, FAÇA O SEGUINTE:"
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Arroz Integral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,INFORMAÇÕES IMPORTANTES,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,INGREDIENTE,NaN,NaN,QUANTIDADE USADA NA RECEITA,QUANTIDADE EMBALAGEM,UN,PREÇO,CUSTO,NaN,TEMPO PARA FAZER A RECEITA EM MINUTOS,NaN,1.2,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Clique em: ""ARQUIVO"" no menu superior e depois..."
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MARGEM DE LUCRO,NaN,1,NaN,NaN,NaN,NaN
7,NaN,Batata Doce,NaN,NaN,1600,1000,g,3,4.8,NaN,CARTÕES E TAGS E EMBALAGENS,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,1. Cartão Agradecimento,NaN,NaN,6,500,um,190,2.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,1. Etiqueta Validade,NaN,NaN,6,500,um,225,2.7,NaN,OUTROS,NaN,0,NaN,NaN,NaN,NaN
10,NaN,1. Lacre Sacola,NaN,NaN,6,500,um,240,2.88,NaN,DESCONTO PARA O CENTO,NaN,0,NaN,NaN,NaN,NaN
11,NaN,1. Mimo,NaN,NaN,6,100,um,50,3,NaN,RENDIMENTO,NaN,1.2,NaN,NaN,NaN,NaN
12,NaN,1. Pote 500ml para Marmitas,NaN,NaN,6,24,um,25,6.25,NaN,ATENÇÃO AO CAMPO RENDIMENTO.\nSe você trabalha...,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,CÁLCULO DO PREÇO,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Custo de materiais,NaN,21.91,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Outros custos,NaN,0,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Custo de horas,NaN,0.350467,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Comissões,NaN,0,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Impostos,NaN,0,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Total parcial,NaN,22.260467,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Margem de lucro,NaN,22.260467,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Custos Fixos,NaN,0.200267,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Custos Variáveis,NaN,0,NaN,NaN,NaN,NaN
28,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,21.91,NaN,Valor da sua hora,NaN,17.523364,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,"Se você vende por UNIDADE, esse é o preço fina...",NaN,NaN,NaN,"Se você vende por CENTO, esse é o preço final ...",NaN,NaN,NaN,NaN,"Se você vende por KILO, preencha no campo bran...",NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,PREÇO FINAL DE VENDA PARA UNIDADES,NaN,NaN,NaN,PREÇO FINAL DE VENDA PARA CENTO,NaN,NaN,NaN,NaN,PESO DA PORÇÃO,PREÇO FINAL DA PORÇÃO,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,37.267668,NaN,NaN,NaN,3726.7668,NaN,NaN,NaN,NaN,0.2,7.453534,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,CUSTO,LUCRO,MARGEM,NaN,CUSTO,NaN,LUCRO,MARGEM,NaN,CUSTO,LUCRO,MARGEM,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,18.425223,18.842445,0.505598,NaN,1842.522252,NaN,1884.244548,0.505598,NaN,3.685045,3.768489,0.505598,NaN,NaN,NaN,NaN

In [15]:
df_sheet_com_cabeçalho = pd.read_excel(arquivo, sheet_name=lista_sheets[0], header=5)

df_sheet_com_cabeçalho.head(25)

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Unnamed: 0,INGREDIENTE,Unnamed: 2,Unnamed: 3,QUANTIDADE USADA NA RECEITA,QUANTIDADE EMBALAGEM,UN,PREÇO,CUSTO,Unnamed: 9,TEMPO PARA FAZER A RECEITA EM MINUTOS,Unnamed: 11,1.2,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Clique em: ""ARQUIVO"" no menu superior e depois..."
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MARGEM DE LUCRO,NaN,1,NaN,NaN,NaN,NaN
2,NaN,Batata Doce,NaN,NaN,1600.0,1000,g,3,4.8,NaN,CARTÕES E TAGS E EMBALAGENS,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1. Cartão Agradecimento,NaN,NaN,6.0,500,um,190,2.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1. Etiqueta Validade,NaN,NaN,6.0,500,um,225,2.7,NaN,OUTROS,NaN,0,NaN,NaN,NaN,NaN
5,NaN,1. Lacre Sacola,NaN,NaN,6.0,500,um,240,2.88,NaN,DESCONTO PARA O CENTO,NaN,0,NaN,NaN,NaN,NaN
6,NaN,1. Mimo,NaN,NaN,6.0,100,um,50,3,NaN,RENDIMENTO,NaN,1.2,NaN,NaN,NaN,NaN
7,NaN,1. Pote 500ml para Marmitas,NaN,NaN,6.0,24,um,25,6.25,NaN,ATENÇÃO AO CAMPO RENDIMENTO.\nSe você trabalha...,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,CÁLCULO DO PREÇO,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Custo de materiais,NaN,21.91,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Outros custos,NaN,0,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Custo de horas,NaN,0.350467,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Comissões,NaN,0,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Impostos,NaN,0,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Total parcial,NaN,22.260467,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Margem de lucro,NaN,22.260467,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Custos Fixos,NaN,0.200267,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,Custos Variáveis,NaN,0,NaN,NaN,NaN,NaN
23,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,21.91,NaN,Valor da sua hora,NaN,17.523364,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_sheet_com_cabeçalho_limpa = df_sheet_com_cabeçalho.dropna(subset=['INGREDIENTE'])

df_sheet_com_cabeçalho_limpa.head(25)

,Unnamed: 0,INGREDIENTE,Unnamed: 2,Unnamed: 3,QUANTIDADE USADA NA RECEITA,QUANTIDADE EMBALAGEM,UN,PREÇO,CUSTO,Unnamed: 9,TEMPO PARA FAZER A RECEITA EM MINUTOS,Unnamed: 11,1.2,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
2,NaN,Batata Doce,NaN,NaN,1600.0,1000,g,3,4.8,NaN,CARTÕES E TAGS E EMBALAGENS,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1. Cartão Agradecimento,NaN,NaN,6.0,500,um,190,2.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1. Etiqueta Validade,NaN,NaN,6.0,500,um,225,2.7,NaN,OUTROS,NaN,0,NaN,NaN,NaN,NaN
5,NaN,1. Lacre Sacola,NaN,NaN,6.0,500,um,240,2.88,NaN,DESCONTO PARA O CENTO,NaN,0,NaN,NaN,NaN,NaN
6,NaN,1. Mimo,NaN,NaN,6.0,100,um,50,3,NaN,RENDIMENTO,NaN,1.2,NaN,NaN,NaN,NaN
7,NaN,1. Pote 500ml para Marmitas,NaN,NaN,6.0,24,um,25,6.25,NaN,ATENÇÃO AO CAMPO RENDIMENTO.\nSe você trabalha...,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,21.91,NaN,Valor da sua hora,NaN,17.523364,NaN,NaN,NaN,NaN
25,NaN,"Se você vende por UNIDADE, esse é o preço fina...",NaN,NaN,NaN,"Se você vende por CENTO, esse é o preço final ...",NaN,NaN,NaN,NaN,"Se você vende por KILO, preencha no campo bran...",NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,PREÇO FINAL DE VENDA PARA UNIDADES,NaN,NaN,NaN,PREÇO FINAL DE VENDA PARA CENTO,NaN,NaN,NaN,NaN,PESO DA PORÇÃO,PREÇO FINAL DA PORÇÃO,NaN,NaN,NaN,NaN,NaN
32,NaN,37.267668,NaN,NaN,NaN,3726.7668,NaN,NaN,NaN,NaN,0.2,7.453534,NaN,NaN,NaN,NaN,NaN
35,NaN,CUSTO,LUCRO,MARGEM,NaN,CUSTO,NaN,LUCRO,MARGEM,NaN,CUSTO,LUCRO,MARGEM,NaN,NaN,NaN,NaN
37,NaN,18.425223,18.842445,0.505598,NaN,1842.522252,NaN,1884.244548,0.505598,NaN,3.685045,3.768489,0.505598,NaN,NaN,NaN,NaN

In [28]:
df_sheet_com_cabeçalho_limpa.reset_index(inplace=True)

In [29]:
linha_do_total = df_sheet_com_cabeçalho_limpa[df_sheet_com_cabeçalho_limpa['INGREDIENTE'] == 'Total'].index[0]

linha_do_total

6

In [33]:
df_limpo = df_sheet_com_cabeçalho_limpa[:linha_do_total]

df_limpo.head(25)

,index,Unnamed: 0,INGREDIENTE,Unnamed: 2,Unnamed: 3,QUANTIDADE USADA NA RECEITA,QUANTIDADE EMBALAGEM,UN,PREÇO,CUSTO,Unnamed: 9,TEMPO PARA FAZER A RECEITA EM MINUTOS,Unnamed: 11,1.2,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,2,NaN,Batata Doce,NaN,NaN,1600.0,1000,g,3,4.8,NaN,CARTÕES E TAGS E EMBALAGENS,NaN,NaN,NaN,NaN,NaN,NaN
1,3,NaN,1. Cartão Agradecimento,NaN,NaN,6.0,500,um,190,2.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,NaN,1. Etiqueta Validade,NaN,NaN,6.0,500,um,225,2.7,NaN,OUTROS,NaN,0,NaN,NaN,NaN,NaN
3,5,NaN,1. Lacre Sacola,NaN,NaN,6.0,500,um,240,2.88,NaN,DESCONTO PARA O CENTO,NaN,0,NaN,NaN,NaN,NaN
4,6,NaN,1. Mimo,NaN,NaN,6.0,100,um,50,3,NaN,RENDIMENTO,NaN,1.2,NaN,NaN,NaN,NaN
5,7,NaN,1. Pote 500ml para Marmitas,NaN,NaN,6.0,24,um,25,6.25,NaN,ATENÇÃO AO CAMPO RENDIMENTO.\nSe você trabalha...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_limpo_colunas_necessarias = df_limpo[['Unnamed: 0', 'INGREDIENTE', 'QUANTIDADE USADA NA RECEITA', 'UN']]

df_limpo_colunas_necessarias['Unnamed: 0'] = sheet_name

df_limpo_colunas_necessarias.head()

   Unnamed: 0              INGREDIENTE  QUANTIDADE USADA NA RECEITA  UN
0         NaN              Batata Doce                       1600.0   g
1         NaN  1. Cartão Agradecimento                          6.0  um
2         NaN     1. Etiqueta Validade                          6.0  um
3         NaN          1. Lacre Sacola                          6.0  um
4         NaN                  1. Mimo                          6.0  um

In [47]:
from unidecode import unidecode

def _norm_local(s: str) -> str:
    """Normaliza: minúsculo, sem acento, sem espaços extras."""
    return unidecode((str(s) or "").strip().lower())

In [49]:
df_limpo_colunas_necessarias['ingrediente_norm'] = (
    df_limpo_colunas_necessarias['INGREDIENTE']
        .astype(str)
        .str.strip()
        .str.lower()
        .apply(unidecode)
)

df_limpo_colunas_necessarias.head()

C:\Users\Matheus\AppData\Local\Temp\ipykernel_9140\4097003141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_limpo_colunas_necessarias['ingrediente_norm'] = (

,INGREDIENTE,QUANTIDADE USADA NA RECEITA,UN,ingrediente_norm
0,Batata Doce,1600.0,g,batata doce
1,1. Cartão Agradecimento,6.0,um,1. cartao agradecimento
2,1. Etiqueta Validade,6.0,um,1. etiqueta validade
3,1. Lacre Sacola,6.0,um,1. lacre sacola
4,1. Mimo,6.0,um,1. mimo

In [50]:
df_limpo_colunas_necessarias_ajuste_un = df_limpo_colunas_necessarias['UN'].apply(lambda x: 'un' if x == 'um' else x)

df_limpo_colunas_necessarias_ajuste_un.head()

0     g
1    un
2    un
3    un
4    un
Name: UN, dtype: object

In [57]:
## codigo consolidado

#Libs

import pandas as pd
from unidecode import unidecode

# Funcoes
def _norm_local(s: str) -> str:
    """Normaliza: minúsculo, sem acento, sem espaços extras."""
    return unidecode((str(s) or "").strip().lower())


arquivo = "data/receitas_brutas.xlsx"

xls = pd.ExcelFile(arquivo)

print('Lista de TODAS as planilhas:', xls.sheet_names)

lista_sheets = xls.sheet_names

lista_sheets = lista_sheets[1:len(lista_sheets)-1]

print('Lista de planilhas úteis:', lista_sheets)

print('Iniciando leitura da planilha...')

df_final = pd.DataFrame()

for sheet in lista_sheets:
    print(f'{sheet} - ⚡Start')

    df_sheet = pd.read_excel(arquivo, sheet_name=sheet,header=5)

    df_sheet = df_sheet.dropna(subset=['INGREDIENTE'])

    df_sheet.reset_index(inplace=True)

    linha_do_total = df_sheet[df_sheet['INGREDIENTE'] == 'Total'].index[0]

    df_sheet = df_sheet[:linha_do_total]

    df_sheet = df_sheet[['Unnamed: 0', 'INGREDIENTE', 'QUANTIDADE USADA NA RECEITA', 'UN']]

    df_sheet['Unnamed: 0'] = sheet

    df_sheet = df_sheet.rename(columns={'Unnamed: 0': 'prato'})

    df_final = pd.concat([df_final, df_sheet], ignore_index=True)

    print(f'{sheet} - ✅ Done \n')

df_final_tratado = df_final.copy()
df_final_tratado['INGREDIENTE'] = (
    df_final_tratado['INGREDIENTE']
        .astype(str)
        .str.strip()
        .str.lower()
        .apply(unidecode)
)

df_final_tratado['prato'] = (
    df_final_tratado['prato']
        .astype(str)
        .str.strip()
        .str.lower()
        .apply(unidecode)
)

df_final_tratado['UN'] = df_final_tratado['UN'].apply(lambda x: 'un' if x == 'um' else x)

quantidade_pratos = df_final_tratado['prato'].nunique()

print(f'Quantidade de pratos únicos: {quantidade_pratos}')

Lista de TODAS as planilhas: ['CADASTRO DE INGREDIENTES', 'Arroz Integral', 'Pão Glúten', 'Creme Aipim', 'Base Bolo', 'Rosca Milho', 'Guisado Base', 'Mousse', 'Molho Branco', 'Canelone', ' Arroz Cozido', 'Frango Primavra', 'Risoto Base', 'Gororoba', 'Canja', 'Risoto de Funghi', 'Risoto Tomate Seco', 'Espaguete + Guisado', 'Porções', 'Mix Farinha', 'Guiado Base', 'Legumes + Guisado', 'Moranga + Guisadinho', 'Batata Doce + Guisadinho', 'Risoto Aspargos', 'Pao de Carne', 'Molho Vermelho', 'Vitamina', 'Pizza', 'Frango Grelhado', 'Molho Guisado', 'Almondegas C Molho', 'Arroz + Feijão', 'Massa Espaguete', 'Fricasse', 'Sanduiche', 'Bolo Assado', 'Guisado', 'Mix', 'Molho Frango', 'Sequilhos', 'Lasanha Abobrinha', 'Pudim', 'Risoto Frango', 'Frango Xadre', 'Salada Mix', 'Bolo Milho', 'Panquecas', 'Espinafre Panquca', 'Teste', 'Picadinho', 'Creme', 'Plan1']
Lista de planilhas úteis: ['Arroz Integral', 'Pão Glúten', 'Creme Aipim', 'Base Bolo', 'Rosca Milho', 'Guisado Base', 'Mousse', 'Molho Branco', 'Canelone', ' Arroz Cozido', 'Frango Primavra', 'Risoto Base', 'Gororoba', 'Canja', 'Risoto de Funghi', 'Risoto Tomate Seco', 'Espaguete + Guisado', 'Porções', 'Mix Farinha', 'Guiado Base', 'Legumes + Guisado', 'Moranga + Guisadinho', 'Batata Doce + Guisadinho', 'Risoto Aspargos', 'Pao de Carne', 'Molho Vermelho', 'Vitamina', 'Pizza', 'Frango Grelhado', 'Molho Guisado', 'Almondegas C Molho', 'Arroz + Feijão', 'Massa Espaguete', 'Fricasse', 'Sanduiche', 'Bolo Assado', 'Guisado', 'Mix', 'Molho Frango', 'Sequilhos', 'Lasanha Abobrinha', 'Pudim', 'Risoto Frango', 'Frango Xadre', 'Salada Mix', 'Bolo Milho', 'Panquecas', 'Espinafre Panquca', 'Teste', 'Picadinho', 'Creme']
Iniciando leitura da planilha...
Arroz Integral - ⚡Start
Arroz Integral - ✅ Done

Pão Glúten - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Pão Glúten - ✅ Done

Creme Aipim - ⚡Start
Creme Aipim - ✅ Done

Base Bolo - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Base Bolo - ✅ Done

Rosca Milho - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Rosca Milho - ✅ Done

Guisado Base - ⚡Start
Guisado Base - ✅ Done

Mousse - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Mousse - ✅ Done

Molho Branco - ⚡Start
Molho Branco - ✅ Done

Canelone - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Canelone - ✅ Done

 Arroz Cozido - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

 Arroz Cozido - ✅ Done

Frango Primavra - ⚡Start
Frango Primavra - ✅ Done

Risoto Base - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Risoto Base - ✅ Done

Gororoba - ⚡Start
Gororoba - ✅ Done

Canja - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Canja - ✅ Done

Risoto de Funghi - ⚡Start
Risoto de Funghi - ✅ Done

Risoto Tomate Seco - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Risoto Tomate Seco - ✅ Done

Espaguete + Guisado - ⚡Start
Espaguete + Guisado - ✅ Done

Porções - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Porções - ✅ Done

Mix Farinha - ⚡Start
Mix Farinha - ✅ Done

Guiado Base - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Guiado Base - ✅ Done

Legumes + Guisado - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Legumes + Guisado - ✅ Done

Moranga + Guisadinho - ⚡Start
Moranga + Guisadinho - ✅ Done

Batata Doce + Guisadinho - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Batata Doce + Guisadinho - ✅ Done

Risoto Aspargos - ⚡Start
Risoto Aspargos - ✅ Done

Pao de Carne - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Pao de Carne - ✅ Done

Molho Vermelho - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Molho Vermelho - ✅ Done

Vitamina - ⚡Start
Vitamina - ✅ Done

Pizza - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Pizza - ✅ Done

Frango Grelhado - ⚡Start
Frango Grelhado - ✅ Done

Molho Guisado - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Molho Guisado - ✅ Done

Almondegas C Molho - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Almondegas C Molho - ✅ Done

Arroz + Feijão - ⚡Start
Arroz + Feijão - ✅ Done

Massa Espaguete - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Massa Espaguete - ✅ Done

Fricasse - ⚡Start
Fricasse - ✅ Done

Sanduiche - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Sanduiche - ✅ Done

Bolo Assado - ⚡Start
Bolo Assado - ✅ Done

Guisado - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Guisado - ✅ Done

Mix - ⚡Start
Mix - ✅ Done

Molho Frango - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Molho Frango - ✅ Done

Sequilhos - ⚡Start
Sequilhos - ✅ Done

Lasanha Abobrinha - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Lasanha Abobrinha - ✅ Done

Pudim - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Pudim - ✅ Done

Risoto Frango - ⚡Start
Risoto Frango - ✅ Done

Frango Xadre - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Frango Xadre - ✅ Done

Salada Mix - ⚡Start
Salada Mix - ✅ Done

Bolo Milho - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Bolo Milho - ✅ Done

Panquecas - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Panquecas - ✅ Done

Espinafre Panquca - ⚡Start
Espinafre Panquca - ✅ Done

Teste - ⚡Start

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Teste - ✅ Done

Picadinho - ⚡Start
Picadinho - ✅ Done

Creme - ⚡Start
Creme - ✅ Done

Quantidade de pratos únicos: 51

c:\Users\Matheus\estancia_dos_ventos\ambiente_virtual\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [58]:
df_final_tratado.to_excel('data/receitas_tratadas.xlsx', index=False)